// ISC License
//
// Copyright (c) 2025-2026 Stephen Seo
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
// OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.

const char *HTML_BODY_FACTORS =
    "<!DOCTYPE html>\n"
    "    <html lang=\"en\">\n"
    "    <head>\n"
    "        <meta charset=\"utf-8\">\n"
    "        <title>Checking Your Browser...</title>\n"
    "        <style>\n"
    "            body {\n"
    "                color: #FFF;\n"
    "                background: #555;\n"
    "                font-family: sans-serif;\n"
    "            }\n"
    "            .center {\n"
    "                text-align: center;\n"
    "                display: block;\n"
    "                margin-left: auto;\n"
    "                margin-right: auto;\n"
    "            }\n"
    "            pre {\n"
    "                font-size: 32px;\n"
    "            }\n"
    "        </style>\n"
    "    </head>\n"
    "    <body>\n"
    "        <h2 class=\"center\">Checking Your Browser...</h2>\n"
    "        <pre id=\"progress\" class=\"center\">Waiting to start "
    "verification...</pre>\n"
    "        <script>\n"
    "            \"use strict\";\n"
    "\n"
    "            const progress_values = [\"-\", \"\\\\\", \"|\", \"/\"];\n"
    "            let progress_idx = 0;\n"
    "            let progress_text = document.getElementById(\"progress\");\n"
    "            function update_anim() {\n"
    "                progress_idx = (progress_idx + 1) % "
    "progress_values.length;\n"
    "                progress_text.innerText = progress_values[\n"
    "                    progress_idx\n"
    "                ];\n"
    "            }\n"
    "            var interval_id = -1;\n"
    "\n"
    "            if (!window.Worker) {\n"
    "                console.warn(\"Workers are not available!?\");\n"
    "            }\n"
    "\n"
    "            const worker = new Worker(\"{JS_FACTORS_URL}\");\n"
    "\n"
    "            worker.addEventListener(\"message\", (message) => {\n"
    "                if (message.data.status === \"done\") {\n"
    "                    if (interval_id >= 0) {\n"
    "                        clearInterval(interval_id);\n"
    "                        interval_id = -1;\n"
    "                    }\n"
    "                    progress_text.innerText = \"Verified.\";\n"
    "                    window.location.reload(true);\n"
    "                } else if (message.data.status === \"error_from_api\") {\n"
    "                    if (interval_id >= 0) {\n"
    "                        clearInterval(interval_id);\n"
    "                        interval_id = -1;\n"
    "                    }\n"
    "                    setTimeout(() => {\n"
    "                        progress_text.innerText = \"Error, verification "
    "failed!\";\n"
    "                    }, 500);\n"
    "                } else if (message.data.status === \"error_decoding\") {\n"
    "                    if (interval_id >= 0) {\n"
    "                        clearInterval(interval_id);\n"
    "                        interval_id = -1;\n"
    "                    }\n"
    "                    setTimeout(() => {\n"
    "                        progress_text.innerText = \"Error, failed to "
    "decode challenge!\";\n"
    "                    }, 500);\n"
    "                } else {\n"
    "                    if (message.data.status === \"Starting...\") {\n"
    "                        if (interval_id >= 0) {\n"
    "                            clearInterval(interval_id);\n"
    "                        }\n"
    "                        interval_id = setInterval(update_anim, 500);\n"
    "                    }\n"
    "                    console.log(message.data.status);\n"
    "                }\n"
    "            });\n"
    "\n"
    "            worker.addEventListener(\"error\", (e) => {\n"
    "                console.error(e.message);\n"
    "                console.error(e.lineno);\n"
    "            });\n"
    "\n"
    "            addEventListener(\"load\", (event) => {\n"
    "                setTimeout(() => {\n"
    "                    worker.postMessage(\"start\");\n"
    "                }, 50);\n"
    "            });\n"
    "        </script>\n"
    "    </body>\n"
    "    </html>\n";

const char *JS_FACTORS_WORKER =
    "\"use strict\";\n"
    "\n"
    "function str_to_value(s) {\n"
    "    let value = 0;\n"
    "    let digit = 0;\n"
    "\n"
    "    for (let idx = s.length; idx-- > 0;) {\n"
    "        let sub_value = parseInt(s[idx]);\n"
    "        for (let didx = 0; didx < digit; ++didx) {\n"
    "            sub_value *= 10;\n"
    "        }\n"
    "        value += sub_value;\n"
    "        ++digit;\n"
    "    }\n"
    "\n"
    "    return value;\n"
    "}\n"
    "\n"
    "function b64_to_val(c) {\n"
    "    c = c.charCodeAt(0);\n"
    "    if (c >= 'A'.charCodeAt(0) && c <= 'Z'.charCodeAt(0)) {\n"
    "        return c - 'A'.charCodeAt(0);\n"
    "    } else if (c >= 'a'.charCodeAt(0) && c <= 'z'.charCodeAt(0)) {\n"
    "        return c - 'a'.charCodeAt(0) + 26;\n"
    "    } else if (c >= '0'.charCodeAt(0) && c <= '9'.charCodeAt(0)) {\n"
    "        return c - '0'.charCodeAt(0) + 52;\n"
    "    } else if (c === '+'.charCodeAt(0)) {\n"
    "        return 62;\n"
    "    } else if (c === '/'.charCodeAt(0)) {\n"
    "        return 63;\n"
    "    } else {\n"
    "        return 0xFF;\n"
    "    }\n"
    "}\n"
    "\n"
    "function val_to_b64(val) {\n"
    "    if (val >= 0 && val <= 25) {\n"
    "        return String.fromCharCode(val + 0x41);\n"
    "    } else if (val >= 26 && val <= 51) {\n"
    "        return String.fromCharCode(val + 0x61 - 26);\n"
    "    } else if (val >= 52 && val <= 61) {\n"
    "        return String.fromCharCode(val + 0x30 - 52);\n"
    "    } else if (val === 62) {\n"
    "        return \"+\";\n"
    "    } else if (val === 63) {\n"
    "        return \"/\";\n"
    "    }\n"
    "\n"
    "    return \"A\";\n"
    "}\n"
    "\n"
    "function revb64_long_div_mod(b64_str, val) {\n"
    "    let result = \"\";\n"
    "    let rem = 0;\n"
    "    for (let idx = 0; idx < b64_str.length; ++idx) {\n"
    "        let b64_val = b64_to_val(b64_str[b64_str.length - 1 - "
    "idx])\n"
    "                    + rem * 64;\n"
    "        let inner_result = val_to_b64(Math.floor(b64_val / val));\n"
    "        if (result.length !== 0 || inner_result !== \"A\") {\n"
    "            result = inner_result + result;\n"
    "        }\n"
    "        rem = b64_val % val;\n"
    "    }\n"
    "    return [result, rem];\n"
    "}\n"
    "\n"
    "function getFactors() {\n"
    "  let ret = [ \"{LARGE_NUMBER}\", 0 ];\n"
    "  let current = 2;\n"
    "  let current_count = 0;\n"
    "  let result = [];\n"
    "  let ticks = 1000000;\n"
    "  while (ret[0].length > 1 || ret[0][0] != \"B\") {\n"
    "      let inner_ret = revb64_long_div_mod(ret[0], current);\n"
    "      if (inner_ret[1] === 0) {\n"
    "          current_count += 1;\n"
    "          ret = inner_ret;\n"
    "      } else {\n"
    "          if (current_count !== 0) {\n"
    "              result.push(String(current) + \"x\" + "
    "String(current_count));\n"
    "          }\n"
    "          if (current === 2) {\n"
    "              current += 1;\n"
    "          } else {\n"
    "              current += 2;\n"
    "          }\n"
    "          current_count = 0;\n"
    "      }\n"
    "      if (--ticks === 0) {\n"
    "          break;\n"
    "      }\n"
    "  }\n"
    "  \n"
    "  if (current_count !== 0) {\n"
    "      result.push(String(current) + \"x\" + String(current_count));\n"
    "  }\n"
    "  \n"
    "  let result_str = \"\";\n"
    "  for (let idx = 0; idx < result.length; ++idx) {\n"
    "    result_str += result[idx] + \" \";\n"
    "  }\n"
    "  result_str = result_str.trim();\n"
    "\n"
    "    let xhr = new XMLHttpRequest();\n"
    "    let url = \"{API_URL}\";\n"
    "    xhr.open(\"POST\", url, true);\n"
    "    xhr.setRequestHeader(\"Content-Type\", \"application/json\");\n"
    "    xhr.onreadystatechange = function () {\n"
    "        if (xhr.readyState === 4) {\n"
    "            if (xhr.status === 200) {\n"
    "                postMessage({status: \"done\"});\n"
    "            } else {\n"
    "                postMessage({status: \"error_from_api\"});\n"
    "            }\n"
    "        }\n"
    "    };\n"
    "    let data = JSON.stringify({\"type\": \"factors\",\n"
    "                               \"id\": \"{UUID}\",\n"
    "                               \"factors\": result_str});\n"
    "    xhr.send(data);\n"
    "}\n"
    "\n"
    "addEventListener(\"message\", (message) => {\n"
    "    if (message.data === \"start\") {\n"
    "        postMessage({status: \"Starting...\"});\n"
    "        getFactors();\n"
    "    } else {\n"
    "        postMessage({status: \"Invalid start message.\"});\n"
    "    }\n"
    "});\n";
